language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn lint
  - yarn build
  - yarn test

notifications:
  slack:
    secure: EO1eW/+wNObMqbo43yWS7IW9Lg8YCI53jlg1uP8g/5RH0YBnH9JEVsVJEltMpiOnEGlcxlD/a8qqw6dmaQvCfbSiiG4IsCYHCddg/YahrbO8y/1nrCI3+/n2XPAaW5mTNio7AMUhsEWT4n0SkErf36aXL28f/Bcvb1hVxahOOYPurgLuUPH0SfZCx417lC7PWh4wwry7tbISFk25UQMVTWFaamb79TCUCTRstz7h1PSRKdkt45JohLbUuQE2cgwL5+vyuxiI7FKtaeKWC7MEOcvEizvsvnzv1tz6Wxcx3oRDElNDB2YqEjsB3/aVmxnwbPypw2+Ovnl+Gz9/5Ie1SYKYk0xHZc6ec7d6tfNdtJZ5SxQgsstcEa8ci/muMSmsDDotCuYPCZoV7v3AqnGJxhK+19dtn3UnZvG7xddNA0W9gxLR7XoJ/LVAe56m9IJoz6yJqskrYvEoyS0E7dU5qC5v/rLyau1/52i2zkeTIPLd45oqqyP10yrPEyWudljPALtljHJpxwYGO2nZEXcYI5fOb11hWGpugNBfPJ161KsDJ6fl836Xu44rnFBpyvOp97yDpcjsXdCGo2RlQpIz+ZSG0Qz2Qc8jYhvlB30jF9gIARJjqty5Z8pdPNvelkwRGKgf1BJPQFpEwhPMmjL9NWlzUJAAAQA994iBToESxI0=

env:
  global:
    - secure: JMeaWgzo4NRaaUnpHdjRSrd8ko7BYbhbKa60aFFH5quI5BOBFzsnvdN+pCqAYW+ZfqjqM5kAsp4BjXGXkCYt/TYCn+Klkh6dA/sZzBkjOOaPdVlQpTzXeP3SLZWFLVxLaCVYUYw0tHecCyUUNFmifowVUQB8VfI6p4zCgr4xIHrRD0IrSiPUeCfLqIhl4AJCKOg8K3b9BgCWtfeDDQXM7VNoAOEfFNqHPUxPdyw5O0sYDM9wiGm0YO7geAoSswuPrCc89eIdV2bGzYLX9oQCoSxAeGnShAJYrRq7G43sbkDf5rXh8Pt8xLuWvbaulStjl+QW1Y3AsDWbTbSESRMmql6Cn+nY7bY9prIVYLl9uUSw6988PbBHlEv4cwG8ZEupOTfQ8eOZh89qMTk5yfCCwRXvVwJyERnMlUkGjHcrjDGUCG/KlfXnVjA+sWagEIvoVHUS/aYUQN6eNOHg8xO21B3+VL9nD5D96e50TT3yAQ0OM/uhIAbHOwU0WzHnVy9a2pZzYq3eC7bRzDfPt2Tldme1JJFHfeWzE0vrXdTaSg91WZ6AuHCBskJGxZyl1zbmNSj+xUSmyB7Ndy5rGMqEMnzw0YDA/AVk9l+e9Ffs4aRI56iuN1KQ9YSMZoiVHu/ndmgx5bpDj2aGCbX1K6YKpARFCtHTr6xfIIq4HxvbcMc=
    - secure: JvMXez9uOA+26ow1QMWO1m8yvmV93F1zeghNuza3C3ZeEwEO9u6TYftYtR8wzXOCwrDt+c+AGB5N48e9Z9jmOs1E2P+CXd319hIcyeNMzikN3xfHprJUXUoXLIidIDnKhduW1MP3+vkrbsAdOtgOplTnc60sPypsPO4r9IoYwsxlvvH34oP8mQ5QLo1qO46ZD0bXvwiQXtXzXQC8vDe70Y6u7GHfSHpfWnROXVhNJd39c4/4I8By5Da37Q1ROIHIKFExUpnwQEiO/isAo15LwBmDZqmKu/CrZy/7zOGbud+qItGmIj8IfdEsAinxKO71CMhy0itWUl84vzZ9TjL0u/CUtwvO71ETGc/p7aUQrT0hKfWw9EW9Zc0GlS1zYHwMsp5ciaUJOJCraOqHDp1LMVxzuCVRvcX+EvEaa3Se+In0wyivMtAyCIUnH/jSxtLRGVteQUEQ/kLcwKQE4aaOMvb0mcwwMLdb5qiKVsH9yusGKvnj4yz/tcusMCrKPheX0djTbJtWTF+8VdbXS84+/uBHU8LJmi+60c3JY+KPkVv4LWKLpksSF4/z+M880KuhGFJwKXcv8f3RRBxEMVZgTwYCsmaq560vrSiZqggh7AMsKAgI7Tc8qVeHSuL7wAJuVVk2GYu+X1tsPpK2lD3gG9o6ocC73sLBLv9qoRyDPqE=
    - secure: SZCyEZLJA6S+V0CXG15644BE6M+swSOkH9gCwh7JhMSHSbu5wNAd//xuLeKiZvoAxzxKSKKcYXjj9oCvPQ1oTn4fsSppIl0mVc3GO3pmhJXLpPS3tEjGjUSrHO0TxsrjX6W0m834I4LuIKdEqn92M6TYYeB8q0mzb/sFBRLlrz1gnlKtvkvmx759OLhqJNqpI5XmaFOuhpoUyn8tOL/Zhdnxu7UJHE65qUYPZqaOzi+QO1yyPv1PjwPBNqpM2e5vwUx+l+fN1VzYyHTv1Ez75YzDNaIR2Crz4riSr7/pQquyS3HhcOCL0GZsjTlzfbE9mhrbLRvK7432ZrD3SHXKu4wYfrohxQrvdA2b5g2zZZjrN55KwIoywpPltLVGxhvu1VRNZBi9g3TDf4wZ7KUvbNFwx/gPlXt/M9QbRqaPIfxcPWwwirBjZYlVy8Nh9aR8ucdrENrP0a4+AwB/DnNcnpYVU6VxVd7sC2mQHj7cZcNYoXSPr/R+p+xedz0/JGyHll0ib+2ufWQ+kS7GOv3bkaS5/h+baqDSr705u/xAKcIq83PS12CKtlCgthFBlpSHXS5yx6J8Hm0ZarmzSqJPYxBtj5Rhu1KHDf47+K1vJOgSx28rlB4XAX/1Z07J9E3Xl4frUaea0LDPvCgnzGOQV/4AAN0hJZcpCANN1MVQg30=
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
